# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#type
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

require 'faker'

puts "🌱  spices..."

User.destroy_all
Build.destroy_all
BuildItem.destroy_all
Item.destroy_all

User.create([
    {
        email: "kurtv0727@gmail.com",
        password_digest: BCrypt::Password.create("1111")
    },
])

puts "🌱  users..."

Build.create([
    {
        title: "My First Build",
        hero: "Gideon",
        info: "This is my first build",
        user_id: User.first.id
    },
    {
        title: "My Second Build",
        hero: "Gadget",
        info: "This is my second build",
        user_id: User.first.id
    },
    {
        title: "My Third Build",
        hero: "Murdock",
        info: "This is my third build",
        user_id: User.first.id
    },
    {
        title: "My Fourth Build",
        hero: "Feng Mao",
        info: "This is my fourth build",
        user_id: User.first.id
    }
])

puts "🌱  builds..."

Item.create([
    {
        name: "Overlord",
        classification: "Tier 3",
        category: "physical_power, health",
        special: "Colossal Cleave: Basic attacks deal (+30% Total Physical Power)(+2% Maximum Health) physical damage in a small area around the Target. Damage ranges from 100%-50% based on the stance between Targets.\nBludgeon: Basic attacks deal (+3.5% Bonus Health) physical damage on-hit.",
        physical_power: 25,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Vanguardian",
        classification: "Tier 3",
        category: "health, magical_armor, tenacity",
        special: "Vanguard: Receiving damage from an Enemy Hero grants you 30 physical armor and 30 magical armor for 4s. While active, damage received from Enemy Heroes refreshes the duration - 60s CD.
        Guardian: Nearby Allied Heroes gain 10 physical armor and 10 magical armor.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 10,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Truesilver Bracelet",
        classification: "Tier 3",
        category: "magical_power, health, magical_armor, ability_haste",
        special: "Reprisal: Casting your ultimate grants you a 250(+15% Bonus Health) shield for 5s. While the shield holds, gain CC immunity. Upon removal, it explodes dealing magical damage to nearby enemies for 60% of the initial strength - 40s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 25,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Marshal",
        classification: "Tier 3",
        category: "magical_power, mana_regen, ability_haste, attack_speed",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 45,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 125,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Crystal Tear",
        classification: "Tier 3",
        category: "magical_power, mana_regen, ability_haste, heal_and_shield_power",
        special: "Elation: Healing or Shielding Allied Heroes grants you both 40 magical power and 20 ability for 5s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 225,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 15,
        omnivamp: 0
    },
    {
        name: "Timewarp",
        classification: "Tier 3",
        category: "magical_power, physical_armor, ability_haste",
        special: "Ferrumancer: Casting an ability grants you 6 magical power and 3 physical armor for 5s,stacking up to 5 times.
        Chime: Every 8s, subtract 1s from all current Basic Ability Cooldowns.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 90,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Requiem",
        classification: "Tier 3",
        category: "magical_power, mana_regen, health, heal_and_shield_power",
        special: "Elegy: When a Hero dies gain a stack of Elegy, up to a maximum of 20 stacks. Each stack grants 1 magical power and 10% base mana regeneration.
        Remembrance: Grant nearby allies 1 physical power and 0.5% lifesteal per stack of Elegy.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 125,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 10,
        omnivamp: 0
    },
    {
        name: "Fire Blossom",
        classification: "Tier 3",
        category: "health, mana, physical_armor",
        special: "Heatwave: Deal 15(+1.5% Bonus Health) magical damage per second to nearby Enemies, increased by 100% against immobilized Targets, and 100% against Monsters.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 275,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Elafrost",
        classification: "Tier 3",
        category: "magical_power, mana, ability_haste, health",
        special: "Frostbite: Basic attacks Slow enemies by 3% for 2s, stacking up to 8 times. Melee basic attacks apply 2 stacks.
        Frostfang: Applying 8 stacks of Frostbite to a Target deals an additional (+10% Maximum Mana) magical damage and Roots them for 1s - 8s CD per Target.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Wellspring",
        classification: "Tier 3",
        category: "magical_power, mana_regen, heal_and_shield_power",
        special: "Vital Waters: Casting an ability heals nearby Allies for 20(+10% Magical Power) over 2s.
        Soothing Waters: Vital Waters heals an additional 10% of your lowest Ally's maximum health. Basic attacks against Enemy Heroes reduce the cooldown of Soothing Waters by 1s - 15 CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 45,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 100,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 20,
        omnivamp: 0
    },
    {
        name: "Golem's Gift",
        classification: "Tier 3",
        category: "magical_power, physical_armor, ability_haste",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 30,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Totem",
        classification: "Tier 3",
        category: "magical_armor, mana_regen, physical_armor, ability_haste, antiheal",
        special: "Chilling Blight: Nearby Enemy Heroes have their healing reduced by 40% and are Slowed by 10%.
        Nirvana: Nearby Allied Heroes receive 15% increased Healing and Shielding.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 30,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Hexbound Bracers",
        classification: "Tier 3",
        category: "physical_armor, mana, ability_haste",
        special: "Meditation: Gain 20 ability haste while above 50% maximum mana.
        Mana Reactor: Restore mana equal to 10% of the damage taken from Enemy Heroes.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 60,
        magical_armor: 0,
        mana: 400,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Galaxy Greaves",
        classification: "Tier 3",
        category: "physical_armor, magical_armor, ability_haste, mana_regen",
        special: "ZeroG: Moving generates stacks of ZeroG, at 100 stacks your next jump will have increased height.
        Celerity: Gain 10% bonus movement speed out of combat.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 30,
        mana: 0,
        mana_regen: 100,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Flux Matrix",
        classification: "Tier 3",
        category: "magical_armor, health, ability_haste",
        special: "Unstable Shackles: Nearby Enemy Heroes take 15% additional magical damage and have their tenacity decreased by 20%.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Dynamo",
        classification: "Tier 3",
        category: "health, physical_armor, mana",
        special: "Immobilizer: Immobilizing an Enemy deals 30(+4% Maximum Health) bonus magical damage to the Target and nearby Enemies, shredding their physical armor and magical armor by 30% for 4s. Damage is increased by 200% against Monsters - 12s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 55,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Breach",
        classification: "Tier 3",
        category: "physical_power, attack_speed, physical_penetration",
        special: "Splinter: Basic Attacks deal 30% of the targets bonus physical armor as bonus physical damage on-hit.
        Puncture: Gain 20% Physical Penetration.",
        physical_power: 35,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 15,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Bonesaw",
        classification: "Tier 3",
        category: "physical_power, health",
        special: "Colossal Sunder: Every third consecutive basic attack deals(+3% Maximum Health) bonus physical damage on-hit and slows the target by 20% for 1s.
        Flurry: Dealing damage with Colossal Sunder grants 6% attack speed for 5s, stacking up to 6 times.",
        physical_power: 20,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 600,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Malady",
        classification: "Tier 3",
        category: "physical_power, physical_penetration, ability_haste",
        special: "Parting Gift: Killing an Enemy Unit causes them to explode in a small radius, dealing (+30% of the Target's Maximum Health) as physical damage. Damage ranges from 100%-40% based on distance between Targets and is capped at 500 - 2s CD.
        Demise: Dealing damage to an Enemy Hero that is below 40% maximum health deals an additional 40(+10% Bonus Physical Power) physical damage, increasing by 10 with each activation. Takedowns reset Demise's cooldown - 45 CD.",
        physical_power: 45,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Azure Core",
        classification: "Tier 3",
        category: "magical_power, mana, ability_haste",
        special: "Font: Killing an Enemy Minion grants 4 bonus mana per stack, up to a maximum of 400. At maximum stacks, gain 10 ability haste.
        Arcane Magic: Grant bonus magical power equal to (+4% Maximum Mana).",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 50,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 350,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Guard",
        classification: "Tier 3",
        category: "health, physical_armor, ability_haste, antiheal",
        special: "Blighted Thorns: When hit by a basic attack, reduce the Source's Healing by 40% and apply a bleed dealing 30(+21% Bonus Physical Armor) magical damage over 3s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Spellbreaker",
        classification: "Tier 3",
        category: "magical_power, magical_armor, ability_haste",
        special: "Veil: Grants a Spell Shield that blocks the next Enemy ability - 60s CD.
        Malefic: Gain 15% increased magical power whil Veil is active.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Dreambinder",
        classification: "Tier 3",
        category: "magical_power, health, tenacity",
        special: "Chilling Spells: Damaging abilites Slow affected Units by 25% for 1s.
        Thaw: Abilities deal 10% additional damage to Slowed Enemy Heroes.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 80,
        magical_penetration: 0,
        health: 250,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 15,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Mesmer",
        classification: "Tier 3",
        category: "physical_power, magical_armor, physical_penetration",
        special: "Vengeful Shroud: Grants a Spell Shield that blocks the next Enemy ability. Upon blocking an enemy ability, gain 30 physical power for 3s - 60s CD.",
        physical_power: 40,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 25,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Demon Edge",
        classification: "Tier 3",
        category: "physical_power, omnivamp",
        special: "Demonic: While above 40% maximum health, increase your bonus physical power by +8%.
        Ceaseless: While below 40% maximum health, gain 5% omnivamp.",
        physical_power: 50,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 5
    },
    {
        name: "Astral Catalyst",
        classification: "Tier 3",
        category: "magical_power, mana, ability_haste",
        special: "Spellsinger: Using an ability grants you 3% increased magical power for 3s, stacking up to 3 times.
        Ravenous: Takedowns refund 20% of your ultimate's total cooldown.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Unbroken Will",
        classification: "Tier 3",
        category: "health, health_regen, magical_armor, tenacity",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 150,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Wraith Leggings",
        classification: "Tier 3",
        category: "magical_power, magical_penetration",
        special: "Spectre: Dealing damage to an Enemy Hero with an Bility grants 100 movement speed for 1.5s.
        Carnage: Abilities deal an additional 20% magical damage against Enemy Heroes below 40% maximum health.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 80,
        magical_penetration: 15,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Warden's Faith",
        classification: "Tier 3",
        category: "health, physical_armor",
        special: "Stalwart: Take 15% reduced damage from Critical Strikes.
        Retribution: When hit by a basic attack, reduce current basic ability cooldowns by 0.2s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 70,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Perforator",
        classification: "Tier 3",
        category: "physical_power, physical_penetration, ability_haste",
        special: "Calamity: Abilities deal 0% − 40% (based on 0-1600 maximum health difference) bonus physical damage against Enemy Heroes with greater maximum health than you.
        Desolate: Your physical damage ignores 35% of target's physical armor(Before Penetration).",
        physical_power: 55,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Blade",
        classification: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Storm Breaker",
        classification: "Tier 3",
        category: "physical_power, attack_speed",
        special: "Chain Zap: Every fourth successful basic attack releases a bolt of lightning which leaps between 7 Targets, dealing 60 (+50% Bonus Physical Power) magical damage and applying on-hit effects to each.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 40,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Stonewall",
        classification: "Tier 3",
        category: "health, physical_armor, health_regen",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 150,
        health_regen: 150,
        physical_armor: 70,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Raiment of Renewal",
        classification: "Tier 3",
        category: "health, health_regen, ability_haste, mana",
        special: "Regenerator: Regenerate 10% of damage taken over 6s.
        Synthesis: Gain Health Regeneration equal to 0.5% of your bonus health.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 600,
        health_regen: 125,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Oathkeeper",
        classification: "Tier 3",
        category: "magical_power, health, ability_haste",
        special: "Celestial Spellblade: After using an ability, your next basic attack within 6s deals (+60% Total Physical Power)(50% Magical Power) bonus magical damage on-hit - 1.5s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Magnify",
        classification: "Tier 3",
        category: "magical_power, ability_haste, attack_speed",
        special: "Shredding Strike: Your basic attacks decrease the Target's magical armor by 6% for 3s, stacking up to 5 times.
        Magnifying Strikes: Basic attacks against Enemy Heroes grants you 8 magical power for 3s, stacking up to 5 times.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 30,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Lightning Hawk",
        classification: "Tier 3",
        category: "physical_power, attack_speed, critical_strike",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 50,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Bastion",
        classification: "Tier 3",
        category: "health, health_regen, magical_armor, antiheal",
        special: "Blighted Veil: Receiving magical damage reduces the Source's Healing by 40% for 3s. 
        Colossus: Gain 6% Damage mitigation, doubled vs Targets affected by Blight.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 150,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Legacy",
        classification: "Tier 3",
        category: "physical_power, ability_haste, magical_armor, tenacity",
        special: "Tenacious Bravery: Dropping below 30% max health cleanses you and grants CC immunity for 3s - 120s CD.
        Resolute: Gain 1 physical power for every 3% missing health, for a maximum of 20 physical power.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 30,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 15,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Dread",
        classification: "Tier 3",
        category: "physical_power, physical_penetration, magical_armor, mana_regen",
        special: "Voracity: Killing an Enemy Target restores 5% of your missing health, increased 25% for Enemy Heroes.
        Celerity: Gain 10% bonus movement speed out of combat.",
        physical_power: 40,
        physical_penetration: 10,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tectonic Mallet",
        classification: "Tier 3",
        category: "physical_power, magical_armor, movement_speed, ability_haste",
        special: "Magnitude: Gain 25% of your bonus movement speed as bonus physical power.
        Harmonic Absorber: While Slowed, gain 10% increased movement speed.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 40,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 5,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Frostguard",
        classification: "Tier 3",
        category: "health, physical_armor, mana, ability_haste",
        special: "Chilling Presence: Slow nearby Enemies by 10% and apply a stack of Stifle every every 0.5s.
        Stifle: When hiy by a basic attack, reduce the Source's total attack speed by 3% for 3s, stacking up to 5 times.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 60,
        magical_armor: 0,
        mana: 250,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Combustion",
        classification: "Tier 3",
        category: "magical_power, magical_penetration, mana",
        special: "Pyro: Your next instance of ability damage will deal 70(+18% Magical Power)bonus magical damage to the Target and nearby Enemies - 12s CD.
        Pyromaniac: Damagin Enemy heroes reduces the cooldown of Pyro by 0.5s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 10,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Citadel",
        classification: "Tier 3",
        category: "physical_power, health, physical_armor",
        special: "Fortification: Gain 10 physical armor for each nearby Enemy Hero.
        Intimidation: Nearby Enemy Heroes have their physical armor decreased by 20%.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Draconium",
        classification: "Tier 3",
        category: "physical_power, ability_haste, physical_armor",
        special: "Surge: Taking or dealing damage generates 2 physical power and 2% increased Healing, stacking up to 10 times. Stacks are lost out of combat.
        Flow: Takedowns restore 12% if your missing health and grant you 3% Attack Speed per stack of Surge for 8s.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Void Helm",
        classification: "Tier 3",
        category: "health, magical_armor, ability_haste",
        special: "Justicar: Every 40 magical damage received, gain 4 magical amor and 75% base health regeneration for 8s, stacking up to 8 times. At maximum stacks, gain 15% movement speed.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 500,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Vanquisher",
        classification: "Tier 3",
        category: "physical_power, physical_penetration, critical_strike",
        special: "Annihilate: If you deal damage that would leave a Hero below 6% of their maximum health, execute them.",
        physical_power: 50,
        physical_penetration: 10,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Scepter",
        classification: "Tier 3",
        category: "magical_power, ability_haste, health, antiheal",
        special: "Blighted Spells: Dealing magical damage to an Enemy Target reduces their Healing by 40% for 3s.
        Malice: Every second, gain a stack of Malice up to a Maximum of 15. Damagin an Enemy Hero with an ability consumes Malice to deal 5(1% MP) true damage per stack. Takedowns grant maximum stakcs of Malice instantly.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Painweaver",
        classification: "Tier 3",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Splice: Casting an ability will grant you 4 physical penetration and 4% movement speed for 4s, stacking up to 4 times.",
        physical_power: 45,
        physical_penetration: 12,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Omen",
        classification: "Tier 3",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Bestial Torment: Moving generates stacks of Torment. At 100 stacks, your next basic attack consumes them to deal 30(40% Bonus Physical Power) bonus physical damage and reduce your current basic ability cooldowns by 1.5s.",
        physical_power: 45,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Nightfall",
        classification: "Tier 3",
        category: "physical_power, physical_penetration",
        special: "Eclipse: Dealing damage to an isolated Enemy Hero (500u) grants 10% attack speed and 10 ability haste for 5s, stacking up to 3 times. At maximum stacks gain 8% omnivamp.",
        physical_power: 45,
        physical_penetration: 12,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Lifebinder",
        classification: "Tier 3",
        category: "magical_power, health, life_steal",
        special: "Vital Bond: Gain (+0.5% bonus health) Ability Haste per 50 Magical Power.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 10,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Infernum",
        classification: "Tier 3",
        category: "physical_power, ability_haste, mana",
        special: "Cinder: Abilities and Basic Attacks apply stacks of Kindling to Enemy Targets for 5s. At 4 stacks, the Kindling ignites dealing (+120% Total Physical Power) Physical Damage over 2s.",
        physical_power: 45,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Deathstalker",
        classification: "Tier 3",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Corrode: Dealing damage to an Enemy Hero reduces their physical armor by 5% for 2s. Stacks up to 6 times.
        Virulence: Your abilities deal 20% bonus true damage against Targets with 6 stacks of Corrode.",
        physical_power: 40,
        physical_penetration: 10,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Crystalline Cuirass",
        classification: "Tier 3",
        category: "magical_armor, ability_haste, health",
        special: "Volatile: When you take ability damage, release a pulse of energy dealing 20(+3% Maximum Health) magical damage to all nearby Enemies - 1.5s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 70,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Basilisk",
        classification: "Tier 3",
        category: "physical_power, ability_haste, health, physical_penetration",
        special: "Corrode: Dealing damage to an Enemy Hero reduces their physical armor by 5% for 2s. Stacks up to 6 times.
        Eminence: Your basic attacks against Targets with 6 stacks of Corrode deal 4% of their missing health as bonus physical damage.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 250,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Terminus",
        classification: "Tier 3",
        category: "physical_power, life_steal, critical_strike",
        special: "Anon: Excess healing from lifesteal is converted to a shield, up to (+80% Total Physical Power) total.The shield slowly decays after 15s of leaving combat.
        Endless: Takedowns grant Anon’s Shield instantly.",
        physical_power: 45,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 12,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Rounds",
        classification: "Tier 3",
        category: "physical_power, attack_speed, critical_strike antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 25,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 30,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Sky Splitter",
        classification: "Tier 3",
        category: "physical_power, attack_speed",
        special: "Rend: Basic attacks deal 3% of the Target's current health as bonus physical damage on-hit.
        MPA: Rend's bonus damage deals a minimum of 10 and is capped at 50 against Monsters and Minions.
        Carve: Every fourth successful basic attack against the same Target within 6s deals 5% of their maximum health as bonus physical damage.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 30,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Absolution",
        classification: "Tier 3",
        category: "physical_power, attack_speed, magical_armor, tenacity",
        special: "Bravery: Gain 25% Damage Mitigation & 40% Movement Speed for 3s when affected by a hard Crowd Control Effect - 60s CD.
        Determined: Gain 1% attack speed for every 3% missing health for a maximum of 20% attack speed.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 20,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 30,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Resolution",
        classification: "Tier 3",
        category: "physical_power, attack_speed, physical_penetration, mana",
        special: "Darksteel: Basic Attacks deal (+6% maximum mana) bonus physical damage on-hit over 5s. Additional applications refresh the duration.
        Basic Attacks restore 3% missing mana on-hit.",
        physical_power: 45,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Viper",
        classification: "Tier 3",
        category: "physical_power, ability_haste, attack_speed, critical_strike",
        special: "Corrode: Dealing damage to an Enemy Hero reduces their physical armor by 5% for 2s. Stacks up to 6 times.
        Diligence: Your Critical Strikes deal 10% more damage against Targets with 6 stacks of Corrode.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Mindrazor",
        classification: "Tier 3",
        category: "physical_power, ability_haste, mana",
        special: "Ingenious Cleave: Dealing damage to an Enemy Unit with a basic attack or ability deals an additional(+25% Total Physical Power) physical damage in a small area around them. Damage ranges from 100% to 50% based on distance between Targets. DOT sources are excluded.
        Potent Font: Killing an Enemy Minion grants 5 bonus Mana, up to a maximum of 400. At maximum stacks, gain 2.5% of your maximum Mana as additional physical power.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Megacosm",
        classification: "Tier 3",
        category: "magical_power, ability_haste, mana",
        special: "Disintegrate: Dealing damage to an Enemy Target with an ability deals 4% of their maximum health as magical damage over 3s. 
        Atomize: Damaging an Enemy Hero affected by Disintegrate with an Ability deals an additional 5% of their maximum health as magical damage - 8s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Kingsbane",
        classification: "Tier 3",
        category: "physical_power, attack_speed, omnivamp, life_steal",
        special: "Chaos: Basic Attacks deal 15 (+10% Bonus Physical Power) additional magical damage on-hit.
        Order: Successful Basic Attacks restore 15 (+10% Bonus Physical Power) health on-hit.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 5
    },    {
        name: "Caustica",
        classification: "Tier 3",
        category: "magical_power, magical_penetration, mana_regen",
        special: "Magus: While above 50% maximum mana, gain 20% magical penetration.
        Arcane Resolve: While below 50% maximum, gain (+1% Maximum Mana)mana regeneration per second.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 80,
        magical_penetration: 20,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "World Breaker",
        classification: "Tier 3",
        category: "magical_power, health, tenacity",
        special: "Fiend: Dealing magical damage to an Enemy Hero increases your magical damage dealt by 4% for 5s, stacking up to 4 times.
        Maya: Gain (2% Maximum Health) bonus magical power.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 45,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 30,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Salvation",
        classification: "Tier 3",
        category: "physical_power, health, tenacity",   
        special: "Aegis: Falling below 40% maximum health grants you a (+20% maximum health) shield (halved for Ranged Heroes) and 10% Omnivamp for 6s - 60s CD.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 500,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 30,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Prophecy",
        classification: "Tier 3",
        category: "magical_power, ability_haste, attack_speed",
        special: "Magical Strikes: Basic attacks deal 15(+20% Magical Power) bonus magical on-hit.
        Hasty: Gain (+60% Ability Haste)% attack speed.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 25,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Mutilator",
        classification: "Tier 3",
        category: "physical_power, ability_haste, omnivamp",
        special: "Mutilate: Basic attacks deal 1% of the Enemy Hero's maximum health as bonus physical damage. Applies twice on non-DOT abilities.
        Devour: Damaging an Enemy Hero with an ability steals 5% of their maximum health for 20s. Can only occur once per Target.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 5
    },    {
        name: "Demolisher",
        classification: "Tier 3",
        category: "physical_power, critical_strike, physical_penetration",
        special: "Decisive Strike: Your next critical strike deals 30% additional physical damage - 12s CD.
        Bore: Gain 25% Physical Penetration.",
        physical_power: 50,
        physical_penetration: 0,
        critical_strike: 20,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Dust Devil",
        classification: "Tier 3",
        category: "physical_power, attack_speed, critical_strike",
        special: "Menace: Critical Strikes grant 2% attack speed for 5s, stacking up to 8 times. At maximum stacks, gain 25 physical power and 15% movement speed.Critical Strikes grant 2x stacks.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 25,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Augmentation",
        classification: "Tier 3",
        category: "physical_power, ability_haste, health",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 250,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Ashbringer",
        classification: "Tier 3",
        category: "physical_power, ability_haste, attack_speed",
        special: "Accelerate: Basic Attacks against Enemy Heroes decrease your current basic ability cooldowns by 0.15s (+0.15s per stack of Clockwork) and grant a stack of Clockwork for 3s, stacking up to 4 times.
        Chrono Strikes: Basic attacks deal 15 (+5 per stack of Clockwork) bonus physical damage on-hit.",
        physical_power: 45,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Oblivion Crown",
        classification: "Tier 3",
        category: "magical_power",
        special: "Annihilate: Increase your magical power by 15%. Oblivion: Your next instance of ability damage against an Enemy Hero will deal an additional 8% of their current health as magic damage and increase their magical damage taken by 10% for 3s - 30s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 120,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Imperator",
        classification: "Tier 3",
        category: "physical_power, critical_strike",
        special: "Precision: Critical Strikes deal 15% more damage.",
        physical_power: 60,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Strength Tonic",
        classification: "Consumable",
        category: "physical_power, omnivamp",
        special: "Consume: Grants 30 physical power and 10% omnivamp for 5 minutes. Effect is lost upon death.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 10
    },
    {
        name: "Stamina Tonic",
        classification: "Consumable",
        category: "health, health_regen",
        special: "Consume: Grants 300 health and 12 health regeneration for 5 minutes. Effect is lost upon death.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 300,
        health_regen: 12,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Protection Tonic",
        classification: "Consumable",
        category: "physical_power, ability_haste, health",
        special: "Grants 20 physical armor, 20 magical armor and 30% tenacity for 5 minutes. Effect is lost upon death.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 20,
        magical_armor: 20,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 30,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Intellect Tonic",
        classification: "Consumable",
        category: "magical_power, mana_regen",
        special: "Consume: Grants 50 magical power and 200% base mana regeneration for 5 minutes. Effect is lost upon death.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 50,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 200,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Nyr Warboots",
        classification: "Crest",
        category: "health, health_regen, physical_armor, magical_armor, movement_speed",
        special: "Active - Resilience: Gain 30% movement speed and store 45% of damage received for 5s. 
        After the duration, regenerate health equal to the damage stored over 3s - 120s CD. 
        Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 175,
        health_regen: 75,
        physical_armor: 8,
        magical_armor: 8,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Saphir's Mantle",
        classification: "Crest",
        category: "health, health_regen, physical_armor, magical_armor",
        special: "Active - Sturdy: Gain (+20% Maximum Health) bonus health for 6s. During this time, dealing damage Slows Enemies by 15% for 1s - 90 CD.
        Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 75,
        physical_armor: 5,
        magical_armor: 10,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Razorback",
        classification: "Crest",
        category: "health, health_regen, physical_armor, magical_armor",
        special: "Active - Echidna: Reflect 50% of damage received from Enemy Heroes as true damage for 4s - 90s CD.
        Creep slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 150,
        health_regen: 50,
        physical_armor: 15,
        magical_armor: 8,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tranquility",
        classification: "Crest",
        category: "ability_haste, magical_power, mana_regen",
        special: "Active - Grace: Heal yourself and nearby Allied heroes for 150(+50% Magical Power) and grant affected Units 10% damage mitigation for 3s. - 30s CD.
        Wealthy Pacifist: Increase Passive Gold Income by 50% and receive dimishing gold from excessive Minion kills.
       Visionary: Gain Solstone and increase your Ward cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 50,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Silentium",
        classification: "Crest",
        category: "magical_power, magical_armor, mana_regen, ability_haste",
        special: "Active - Muzzle: Silence an Enemy Hero for 1.5s. If Muzzle interrupts an ability, deal 150 (+50% Magical Power)(+50% Bonus Physical Power) magical damage to the Target - 120s CD.
        Wealthy Pacifist: Increase Passive Gold Income by 50% and receive diminishing gold for excessive Minion kills.
        Visionary: Gain Solstone and increase your Ward Cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 25,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 10,
        mana: 0,
        mana_regen: 75,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Sanctification",
        classification: "Crest",
        category: "health, health_regen, mana_regen",
        special: "Active - Safeguard: Grants yourself and nearby Allied Heroes 250(+12% of your Maximum Health) shield for 3s. While the shield holds, Heroes gain 60% tenacity - 120 CD.
        Wealthy Pacifist: Increase Passive Gold Income by 50% and receive diminishing gold from excessive Minion kills.
        Visionary: Gain Solstone and increase your Ward Cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 75,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 75,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Rift Walkers",
        classification: "Crest",
        category: "magical_power, health, health_regen, mana",
        special: "Active - Rift Snatcher: Dash forward a short distance and pull all nearby enemies towards you. Enemies pulled by Rift Snatcher take 15% increased damage for 3s - 120 CD.
        Wealthy Pacifist:  Increase Passive Gold Income by 50% and receive diminishing gold from excessive Minion kills.
        Visionary: Gain Solstone and increase your Ward Cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 15,
        magical_penetration: 0,
        health: 150,
        health_regen: 100,
        physical_armor: 0,
        magical_armor: 0,
        mana: 100,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Reclamation",
        classification: "Crest",
        category: "magical_power, physical_armor, mana_regen, ability_haste",
        special: "Active - Purify: Cleanse and Heal yourself and nearby Allied Heroes for 150 health over 3s - 150s CD.
        Visionary: Gain Solstone and increase your Ward Cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 12,
        magical_armor: 0,
        mana: 0,
        mana_regen: 75,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Leaf Song",
        classification: "Crest",
        category: "health, health_regen, ability_haste",
        special: "Active - Phantom Rush: Increase the movement speed of yourself and nearby Allies by 50% for 4s. Heroes affected by Phantom Rush are immune to Slows and may pass through Enemy Heroes - 120s CD.
        Wealthy Pacifist: Increase Passive Gold Income by 50% and receive dimishing gold from excessive Minion kills.
        Visionary: Gain Solstone and increase your Ward Cap from 2 to 3.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 180,
        health_regen: 50,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Typhoon",
        classification: "Crest",
        category: "magic_power, health, magical_penetration, attack_speed",
        special: "Cyclone: Basic attacks grant a stack of Cyclone for 3s, increasing your attack speed by 2(+2% Magical Power)%. Cyclone stacks up to 6 times.
        Active - Mirage: When at maximum stacks of Cyclone, dash a short distance and reduce current basic ability cooldowns by 3s - 30s CD.
       Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 8,
        health: 100,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 15,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Time Flux Band",
        classification: "Crest",
        category: "magical_power, mana, magical_penetration, ability_haste",
        special: "Activate - Turntable: Mark your current location and gain 20% movement speed for 4s. After 4s, teleport back to marked location and reset your basic ability cooldowns - 90s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 8,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 150,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tempest",
        classification: "Crest",
        category: "magical_power, health, magical_penetration, ability_haste",
        special: "Active - Overcharge: Overchage for 8s causing lightning to zap up to 3 nearby Enemy Heroes each second, dealing 20(14% Magical Power) magical damage and healing to the damage dealt. Multiple strikes against the same Target deal 50% reduced damage - 90s CD.
        Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 15,
        magical_penetration: 8,
        health: 150,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Soulbearer",
        classification: "Crest",
        category: "magical_power, mana, magical_penetration, ability_haste",
        special: "Active - Anima: Gain a (+25% maximum mana) shield, 20% magical lifesteal and 10% movement speed for 8s - 90 CD.
        Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 15,
        magical_penetration: 8,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Obelisk",
        classification: "Crest",
        category: "magic_power, health, magical_penetration",
        special: "Active - Condemn: Enhance your next basic attack to deal 80(+30% Magical Power)(+15 per Soul) additional magic damage. If a Target struck by Condemn dies within 4s, gain a Soul - 30s CD.
        Soul Stealer: When you achieve a Takedown, gain a Soul which permanently grants you 2 magical power.
        Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 35,
        magical_penetration: 8,
        health: 100,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Epoch",
        classification: "Crest",
        category: "magical_power, mana, magical_penetration, health",
        special: "Enter Stasis for 2.5s, rendering yourself Invulnerable for the duration but unable to move, attack or use abilities - 120s CD.
        Creep Slayer: Deal 40 extra basic damage to Minions.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 25,
        magical_penetration: 8,
        health: 100,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 150,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Iceskorn Talons",
        classification: "Crest",
        category: "physical_power, ability_haste, health",
        special: "Active - Glacial Colosseum: Create a dueling zone around you in a large area that remains for 15s. Yourself and Allied Heroes within the zone gain 15% increased Physical Power and 15% bonus movementspeed for 3s. Enemy Units within the zone are Slowed by 15% - 40s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 15,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 150,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Fenix",
        classification: "Crest",
        category: "physical_power, health",
        special: "Active - Rebirth: Mark your current location and resurrect at the mark with 40% maximum health and mana should you die within the next 4s - 210s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 100,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Brutallax",
        classification: "Crest",
        category: "physical_power, life_steal, health",
        special: "Active - Purifying Rage: Cleanse all Negative Debuffs, then gain 60% tenacity for 8s. Successful basic attacks extend this duration by 0.5s on-hit - 150s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 20,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 5,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Pacifier",
        classification: "Crest",
        category: "physical_power, attack_speed, life_steal",
        special: "Active - Adrenalize: Dash a short distance and empower your next basic attack within 6s to deal 40 (+20% Bonus Physical Power) additional physical damage, doubled against Targets below 40% maximum health. Killing an Enemy Hero within 6s allows Adrenalize to be recast for 10s - 120s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 20,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 10,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 5,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Liberator",
        classification: "Crest",
        category: "physical_power, attack_speed, life_steal",
        special: "Active - Purifying Guard: Cleanse all Negative Debuffs and gain a 100 (+10 per level)(+150% Bonus Physical Power) shield for 2.5s - 150s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 15,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 15,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 8,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Eviscerator",
        classification: "Crest",
        category: "physical_power, attack_speed, life_steal",
        special: "Active - Rending Strikes: Upon activation, gain 10% attack speed and empower your basic attacks to deal (+18% Total Physical Power) true damage on-hit for 6s, increasing by (+3% Total Physical Power) for each successful hit against Enemy Heroes - 90s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 12,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 5,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Witchstalker",
        classification: "Crest",
        category: "physical_power, ability_haste, physical_penetration, omnivamp",
        special: "Active - Purifying Strike: Cleanse all Negative Debuffs and empower your next basic attack or damaging ability against an Enemy Hero to deal 4%(4% per effect removed) of their maximum health as bonus true damage, healing you for an equal amount.
        Creep Slayer: Deal 30 extra basic damage to Minions. - 150 CD",
        physical_power: 15,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 4,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 6
    },
    {
        name: "Ortus",
        classification: "Crest",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Active - Limit Breaker: Upon activation, gain 20% movement speed and 10% increased physical power for 6s. Takedowns within the duration permanently grant 3 physical power and refresh the duration - 90s CD.
        Creep Slayer: Deal 30 extra basic damage to Minions.",
        physical_power: 15,
        physical_penetration: 10,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Nex",
        classification: "Crest",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Active - Reap: Dash a short distance and deal (+100% Bonus Physical Power)(+100% of Sow) physical damage to all nearby Enemy Heroes and Slow them by 80% for 1s - 90s CD.
        Sow: Store 30% of damage dealtto Enemy heroes(15% for AOE abilities) in the past 5s as Sow. Sow charges are expended upon using Reap.",
        physical_power: 20,
        physical_penetration: 10,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    }
])

puts "Items created"


