# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

require 'faker'

puts "🌱  spices..."

User.destroy_all
Build.destroy_all
Build_item.destroy_all
Item.destroy_all

User.create([
    {
        email: "kurtv0727@gmail.com",
        password_digest: BCrypt::Password.create("1111")
    },
])

puts "🌱  users..."

Build.create([
    {
        title: "My First Build",
        hero: "Gideon",
        info: "This is my first build",
        user_id: User.first.id
    },
    {
        title: "My Second Build",
        hero: "Gadget",
        info: "This is my second build",
        user_id: User.first.id
    },
    {
        title: "My Third Build",
        hero: "Murdock",
        info: "This is my third build",
        user_id: User.first.id
    },
    {
        title: "My Fourth Build",
        hero: "Feng Mao",
        info: "This is my fourth build",
        user_id: User.first.id
    }
])

puts "🌱  builds..."

Item.create([
    {
        name: "Overlord",
        type: "Tier 3",
        category: "physical_power, health",
        special: "Colossal Cleave: Basic attacks deal (+30% Total Physical Power)(+2% Maximum Health) physical damage in a small area around the Target. Damage ranges from 100%-50% based on the stance between Targets.
        Bludgeon: Basic attacks deal (+3.5% Bonus Health) physical damage on-hit.",
        physical_power: 25,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Vanguardian",
        type: "Tier 3",
        category: "health, magical_armor, tenacity",
        special: "Vanguard: Receiving damage from an Enemy Hero grants you 30 physical armor and 30 magical armor for 4s. While active, damage received from Enemy Heroes refreshes the duration - 60s CD.
        Guardian: Nearby Allied Heroes gain 10 physical armor and 10 magical armor.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 10,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Truesilver Bracelet",
        type: "Tier 3",
        category: "magical_power, health, magical_armor, ability_haste",
        special: "Reprisal: Casting your ultimate grants you a 250(+15% Bonus Health) shield for 5s. While the shield holds, gain CC immunity. Upon removal, it explodes dealing magical damage to nearby enemies for 60% of the initial strength - 40s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 25,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Marshal",
        type: "Tier 3",
        category: "magical_power, mana_regen, ability_haste, attack_speed",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 45,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 125,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Crystal Tear",
        type: "Tier 3",
        category: "magical_power, mana_regen, ability_haste, heal_and_shield_power",
        special: "Elation: Healing or Shielding Allied Heroes grants you both 40 magical power and 20 ability for 5s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 225,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 15,
        omnivamp: 0
    },
    {
        name: "Timewarp",
        type: "Tier 3",
        category: "magical_power, physical_armor, ability_haste",
        special: "Ferrumancer: Casting an ability grants you 6 magical power and 3 physical armor for 5s,stacking up to 5 times.
        Chime: Every 8s, subtract 1s from all current Basic Ability Cooldowns.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 90,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Requiem",
        type: "Tier 3",
        category: "magical_power, mana_regen, health, heal_and_shield_power",
        special: "Elegy: When a Hero dies gain a stack of Elegy, up to a maximum of 20 stacks. Each stack grants 1 magical power and 10% base mana regeneration.
        Remembrance: Grant nearby allies 1 physical power and 0.5% lifesteal per stack of Elegy.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 20,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 125,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 10,
        omnivamp: 0
    },
    {
        name: "Fire Blossom",
        type: "Tier 3",
        category: "health, mana, physical_armor",
        special: "Heatwave: Deal 15(+1.5% Bonus Health) magical damage per second to nearby Enemies, increased by 100% against immobilized Targets, and 100% against Monsters.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 275,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Elafrost",
        type: "Tier 3",
        category: "magical_power, mana, ability_haste, health",
        special: "Frostbite: Basic attacks Slow enemies by 3% for 2s, stacking up to 8 times. Melee basic attacks apply 2 stacks.
        Frostfang: Applying 8 stacks of Frostbite to a Target deals an additional (+10% Maximum Mana) magical damage and Roots them for 1s - 8s CD per Target.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Wellspring",
        type: "Tier 3",
        category: "magical_power, mana_regen, heal_and_shield_power",
        special: "Vital Waters: Casting an ability heals nearby Allies for 20(+10% Magical Power) over 2s.
        Soothing Waters: Vital Waters heals an additional 10% of your lowest Ally's maximum health. Basic attacks against Enemy Heroes reduce the cooldown of Soothing Waters by 1s - 15 CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 45,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 100,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 20,
        omnivamp: 0
    },
    {
        name: "Golem's Gift",
        type: "Tier 3",
        category: "magical_power, physical_armor, ability_haste",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 30,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Totem",
        type: "Tier 3",
        category: "magical_armor, mana_regen, physical_armor, ability_haste, antiheal",
        special: "Chilling Blight: Nearby Enemy Heroes have their healing reduced by 40% and are Slowed by 10%.
        Nirvana: Nearby Allied Heroes receive 15% increased Healing and Shielding.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 30,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Hexbound Bracers",
        type: "Tier 3",
        category: "physical_armor, mana, ability_haste",
        special: "Meditation: Gain 20 ability haste while above 50% maximum mana.
        Mana Reactor: Restore mana equal to 10% of the damage taken from Enemy Heroes.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 60,
        magical_armor: 0,
        mana: 400,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Galaxy Greaves",
        type: "Tier 3",
        category: "physical_armor, magical_armor, ability_haste, mana_regen",
        special: "ZeroG: Moving generates stacks of ZeroG, at 100 stacks your next jump will have increased height.
        Celerity: Gain 10% bonus movement speed out of combat.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 30,
        mana: 0,
        mana_regen: 100,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Flux Matrix",
        type: "Tier 3",
        category: "magical_armor, health, ability_haste",
        special: "Unstable Shackles: Nearby Enemy Heroes take 15% additional magical damage and have their tenacity decreased by 20%.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Dynamo",
        type: "Tier 3",
        category: "health, physical_armor, mana",
        special: "Immobilizer: Immobilizing an Enemy deals 30(+4% Maximum Health) bonus magical damage to the Target and nearby Enemies, shredding their physical armor and magical armor by 30% for 4s. Damage is increased by 200% against Monsters - 12s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 55,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Breach",
        type: "Tier 3",
        category: "physical_power, attack_speed, physical_penetration",
        special: "Splinter: Basic Attacks deal 30% of the targets bonus physical armor as bonus physical damage on-hit.
        Puncture: Gain 20% Physical Penetration.",
        physical_power: 35,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 15,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Bonesaw",
        type: "Tier 3",
        category: "physical_power, health",
        special: "Colossal Sunder: Every third consecutive basic attack deals(+3% Maximum Health) bonus physical damage on-hit and slows the target by 20% for 1s.
        Flurry: Dealing damage with Colossal Sunder grants 6% attack speed for 5s, stacking up to 6 times.",
        physical_power: 20,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 600,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Malady",
        type: "Tier 3",
        category: "physical_power, physical_penetration, ability_haste",
        special: "Parting Gift: Killing an Enemy Unit causes them to explode in a small radius, dealing (+30% of the Target's Maximum Health) as physical damage. Damage ranges from 100%-40% based on distance between Targets and is capped at 500 - 2s CD.
        Demise: Dealing damage to an Enemy Hero that is below 40% maximum health deals an additional 40(+10% Bonus Physical Power) physical damage, increasing by 10 with each activation. Takedowns reset Demise's cooldown - 45 CD.",
        physical_power: 45,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Azure Core",
        type: "Tier 3",
        category: "magical_power, mana, ability_haste",
        special: "Font: Killing an Enemy Minion grants 4 bonus mana per stack, up to a maximum of 400. At maximum stacks, gain 10 ability haste.
        Arcane Magic: Grant bonus magical power equal to (+4% Maximum Mana).",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 50,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 350,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Guard",
        type: "Tier 3",
        category: "health, physical_armor, ability_haste, antiheal",
        special: "Blighted Thorns: When hit by a basic attack, reduce the Source's Healing by 40% and apply a bleed dealing 30(+21% Bonus Physical Armor) magical damage over 3s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 0,
        physical_armor: 40,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Spellbreaker",
        type: "Tier 3",
        category: "magical_power, magical_armor, ability_haste",
        special: "Veil: Grants a Spell Shield that blocks the next Enemy ability - 60s CD.
        Malefic: Gain 15% increased magical power whil Veil is active.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Dreambinder",
        type: "Tier 3",
        category: "magical_power, health, tenacity",
        special: "Chilling Spells: Damaging abilites Slow affected Units by 25% for 1s.
        Thaw: Abilities deal 10% additional damage to Slowed Enemy Heroes.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 80,
        magical_penetration: 0,
        health: 250,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 15,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Mesmer",
        type: "Tier 3",
        category: "physical_power, magical_armor, physical_penetration",
        special: "Vengeful Shroud: Grants a Spell Shield that blocks the next Enemy ability. Upon blocking an enemy ability, gain 30 physical power for 3s - 60s CD.",
        physical_power: 40,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 25,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Demon Edge",
        type: "Tier 3",
        category: "physical_power, omnivamp",
        special: "Demonic: While above 40% maximum health, increase your bonus physical power by +8%.
        Ceaseless: While below 40% maximum health, gain 5% omnivamp.",
        physical_power: 50,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 5
    },
    {
        name: "Astral Catalyst",
        type: "Tier 3",
        category: "magical_power, mana, ability_haste",
        special: "Spellsinger: Using an ability grants you 3% increased magical power for 3s, stacking up to 3 times.
        Ravenous: Takedowns refund 20% of your ultimate's total cooldown.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Unbroken Will",
        type: "Tier 3",
        category: "health, health_regen, magical_armor, tenacity",
        special: "Sheriff: Yourself and nearby Allied heroes gain 20 attack speed and deal 15(+1 per Target's level) magical damage on-hit.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 150,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Wraith Leggings",
        type: "Tier 3",
        category: "magical_power, magical_penetration",
        special: "Spectre: Dealing damage to an Enemy Hero with an Bility grants 100 movement speed for 1.5s.
        Carnage: Abilities deal an additional 20% magical damage against Enemy Heroes below 40% maximum health.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 80,
        magical_penetration: 15,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Warden's Faith",
        type: "Tier 3",
        category: "health, physical_armor",
        special: "Stalwart: Take 15% reduced damage from Critical Strikes.
        Retribution: When hit by a basic attack, reduce current basic ability cooldowns by 0.2s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 300,
        health_regen: 0,
        physical_armor: 70,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Perforator",
        type: "Tier 3",
        category: "physical_power, physical_penetration, ability_haste",
        special: "Calamity: Abilities deal 0% − 40% (based on 0-1600 maximum health difference) bonus physical damage against Enemy Heroes with greater maximum health than you.
        Desolate: Your physical damage ignores 35% of target's physical armor(Before Penetration).",
        physical_power: 55,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Storm Breaker",
        type: "Tier 3",
        category: "physical_power, attack_speed",
        special: "Chain Zap: Every fourth successful basic attack releases a bolt of lightning which leaps between 7 Targets, dealing 60 (+50% Bonus Physical Power) magical damage and applying on-hit effects to each.",
        physical_power: 30,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 40,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
    {
        name: "Stonewall",
        type: "Tier 3",
        category: "health, physical_armor, health_regen",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 150,
        health_regen: 150,
        physical_armor: 70,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Raiment of Renewal",
        type: "Tier 3",
        category: "health, health_regen, ability_haste, mana",
        special: "Regenerator: Regenerate 10% of damage taken over 6s.
        Synthesis: Gain Health Regeneration equal to 0.5% of your bonus health.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 600,
        health_regen: 125,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Oathkeeper",
        type: "Tier 3",
        category: "magical_power, health, ability_haste",
        special: "Celestial Spellblade: After using an ability, your next basic attack within 6s deals (+60% Total Physical Power)(50% Magical Power) bonus magical damage on-hit - 1.5s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 25,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Magnify",
        type: "Tier 3",
        category: "magical_power, ability_haste, attack_speed",
        special: "Shredding Strike: Your basic attacks decrease the Target's magical armor by 6% for 3s, stacking up to 5 times.
        Magnifying Strikes: Basic attacks against Enemy Heroes grants you 8 magical power for 3s, stacking up to 5 times.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 30,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Lightning Hawk",
        type: "Tier 3",
        category: "physical_power, attack_speed, critical_strike",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 50,
        physical_penetration: 0,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Bastion",
        type: "Tier 3",
        category: "health, health_regen, magical_armor, antiheal",
        special: "Blighted Veil: Receiving magical damage reduces the Source's Healing by 40% for 3s. 
        Colossus: Gain 6% Damage mitigation, doubled vs Targets affected by Blight.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 350,
        health_regen: 150,
        physical_armor: 0,
        magical_armor: 35,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Legacy",
        type: "Tier 3",
        category: "physical_power, ability_haste, magical_armor, tenacity",
        special: "Tenacious Bravery: Dropping below 30% max health cleanses you and grants CC immunity for 3s - 120s CD.
        Resolute: Gain 1 physical power for every 3% missing health, for a maximum of 20 physical power.",
        physical_power: 40,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 30,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 15,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Dread",
        type: "Tier 3",
        category: "physical_power, physical_penetration, magical_armor, mana_regen",
        special: "Voracity: Killing an Enemy Target restores 5% of your missing health, increased 25% for Enemy Heroes.
        Celerity: Gain 10% bonus movement speed out of combat.",
        physical_power: 40,
        physical_penetration: 10,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 30,
        mana: 0,
        mana_regen: 150,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tectonic Mallet",
        type: "Tier 3",
        category: "physical_power, magical_armor, movement_speed, ability_haste",
        special: "Magnitude: Gain 25% of your bonus movement speed as bonus physical power.
        Harmonic Absorber: While Slowed, gain 10% increased movement speed.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 40,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 5,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Frostguard",
        type: "Tier 3",
        category: "health, physical_armor, mana, ability_haste",
        special: "Chilling Presence: Slow nearby Enemies by 10% and apply a stack of Stifle every every 0.5s.
        Stifle: When hiy by a basic attack, reduce the Source's total attack speed by 3% for 3s, stacking up to 5 times.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 60,
        magical_armor: 0,
        mana: 250,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Combustion",
        type: "Tier 3",
        category: "magical_power, magical_penetration, mana",
        special: "Pyro: Your next instance of ability damage will deal 70(+18% Magical Power)bonus magical damage to the Target and nearby Enemies - 12s CD.
        Pyromaniac: Damagin Enemy heroes reduces the cooldown of Pyro by 0.5s.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 10,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 300,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Citadel",
        type: "Tier 3",
        category: "physical_power, health, physical_armor",
        special: "Fortification: Gain 10 physical armor for each nearby Enemy Hero.
        Intimidation: Nearby Enemy Heroes have their physical armor decreased by 20%.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Draconium",
        type: "Tier 3",
        category: "physical_power, ability_haste, physical_armor",
        special: "Surge: Taking or dealing damage generates 2 physical power and 2% increased Healing, stacking up to 10 times. Stacks are lost out of combat.
        Flow: Takedowns restore 12% if your missing health and grant you 3% Attack Speed per stack of Surge for 8s.",
        physical_power: 35,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 35,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 10,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Void Helm",
        type: "Tier 3",
        category: "health, magical_armor, ability_haste",
        special: "Justicar: Every 40 magical damage received, gain 4 magical amor and 75% base health regeneration for 8s, stacking up to 8 times. At maximum stacks, gain 15% movement speed.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 30,
        magical_penetration: 0,
        health: 500,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Vanquisher",
        type: "Tier 3",
        category: "physical_power, physical_penetration, critical_strike",
        special: "Annihilate: If you deal damage that would leave a Hero below 6% of their maximum health, execute them.",
        physical_power: 50,
        physical_penetration: 10,
        critical_strike: 25,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Scepter",
        type: "Tier 3",
        category: "magical_power, ability_haste, health, antiheal",
        special: "Blighted Spells: Dealing magical damage to an Enemy Target reduces their Healing by 40% for 3s.
        Malice: Every second, gain a stack of Malice up to a Maximum of 15. Damagin an Enemy Hero with an ability consumes Malice to deal 5(1% MP) true damage per stack. Takedowns grant maximum stakcs of Malice instantly.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 70,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Painweaver",
        type: "Tier 3",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Splice: Casting an ability will grant you 4 physical penetration and 4% movement speed for 4s, stacking up to 4 times.",
        physical_power: 45,
        physical_penetration: 12,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 15,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Omen",
        type: "Tier 3",
        category: "physical_power, ability_haste, physical_penetration",
        special: "Bestial Torment: Moving generates stacks of Torment. At 100 stacks, your next basic attack consumes them to deal 30(40% Bonus Physical Power) bonus physical damage and reduce your current basic ability cooldowns by 1.5s.",
        physical_power: 45,
        physical_penetration: 8,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 20,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Nightfall",
        type: "Tier 3",
        category: "physical_power, physical_penetration",
        special: "Eclipse: Dealing damage to an isolated Enemy Hero (500u) grants 10% attack speed and 10 ability haste for 5s, stacking up to 3 times. At maximum stacks gain 8% omnivamp.",
        physical_power: 45,
        physical_penetration: 12,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Lifebinder",
        type: "Tier 3",
        category: "magical_power, health, life_steal",
        special: "Vital Bond: Gain (+0.5% bonus health) Ability Haste per 50 Magical Power.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 60,
        magical_penetration: 0,
        health: 200,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 10,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Infernum",
        type: "Tier 3",
        category: "physical_power, ability_haste, mana",
        special: "Cinder: Abilities and Basic Attacks apply stacks of Kindling to Enemy Targets for 5s. At 4 stacks, the Kindling ignites dealing (+120% Total Physical Power) Physical Damage over 2s.",
        physical_power: 45,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 200,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 20,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },    {
        name: "Tainted Blade",
        type: "Tier 3",
        category: "physical_power, ability_haste, health, antiheal",
        special: "Blighted Strikes: Dealing physical damage to an Enemy Target reduces their Healing by 40 % for 3s.
        Hex: Damaging an Enemy Target affected by Blight with an ability deals an additional 20 physical damage and causes them to take 10% more damage for 3s - 1s CD.",
        physical_power: 0,
        physical_penetration: 0,
        critical_strike: 0,
        magical_power: 0,
        magical_penetration: 0,
        health: 0,
        health_regen: 0,
        physical_armor: 0,
        magical_armor: 0,
        mana: 0,
        mana_regen: 0,
        attack_speed: 0,
        ability_haste: 0,
        movement_speed: 0,
        tenacity: 0,
        life_steal: 0,
        magical_life_steal: 0,
        heal_and_shield_power: 0,
        omnivamp: 0
    },
])


